### PR TITLE
fix(Wallet): derive accounts from imported mnemonic and store correctly

### LINKED ISSUE #787: Send Transaction Modal fix: Send from an imported account
Sending *from* an imported account does not work, with an error from StatusGo `cannot locate account for address: 0x123...`.

To reproduce 
1. Import a wallet account via seed
2. Click "Send" to open the send tx modal
3. Select the imported account in the "From account" field
4. Select any recipient, amount, and gas value. Then sign the tx.

Expected: transaction should succeed.
Actual: `cannot locate account for address: 0x123...`

### PR DESCRIPTION
**Pull request by PascalPrecht**
This commit address two bugs:

1. When importing a mnemonic, the resulting "master" account and its address
  was used as account to be stored as opposed to its derived default account
2. The account was stored in the wrong path, resulting in status not being able
  to locate accounts when sending transactions.

Fixes #787

### CODE REVIEW

File: src/status/libstatus/accounts.nim [hunk 1]
```diff
@@ -225,7 +225,7 @@ proc storeDerivedWallet*(account: GeneratedAccount, password: string, walletInde
   let hashedPassword = hashPassword(password)
   let multiAccount = %* {
     "accountID": account.id,
-    "paths": ["m/" & $walletIndex],
+    "paths": ["m/44'/60'/0'/0/" & $walletIndex],
```
Comment (PascalPrecht) [inline src/status/libstatus/accounts.nim:228]: Okay, few things to note here:

This function `storeDerivedWallet` is called as part of `saveAccount` here:

https://github.com/status-im/nim-status-client/blob/68aafaba6fdee1521bdf6075f35b1e6b75a2f2a6/src/status/libstatus/accounts.nim#L241-L242

Notice how it's only called if the given `GeneratedAccount` is considered a **derived account**. This has confused me a lot. The account passed in this particular scenario is **not** a derived account, but the "master" account we get from importing the mnemonic here: 

https://github.com/status-im/nim-status-client/blob/68aafaba6fdee1521bdf6075f35b1e6b75a2f2a6/src/status/wallet.nim#L189

So **actually**, `isADerivedAAccount` should be set to `false` here: 

https://github.com/status-im/nim-status-client/blob/68aafaba6fdee1521bdf6075f35b1e6b75a2f2a6/src/status/wallet.nim#L190

However, that would mean, we would not call `storeDerivedWallet` at all, which doesn't seem to be correct either, because we have to store it so it can be used for transactions...

So after having tons of back and forth discussions with @gravityblast we came to the conclusion that the path here needs to be changed. This makes everything work nicely, but I'm not sure if this function was/is supposed to be used in other scenarios where the wallet/account should be stored in a different path.

Also, I assume it was set to `m/0` for a reason.

I checked the code base and this function is only used in the case when a user imports an account inside of the wallet. So it should be fine for now.

Please let me know if I'm missing anything here @jrainville @richard-ramos

File: src/status/wallet.nim [hunk 2]
```diff
@@ -186,7 +186,8 @@ proc generateNewAccount*(self: WalletModel, password: string, accountName: strin
 
 proc addAccountsFromSeed*(self: WalletModel, seed: string, password: string, accountName: string, color: string): string =
   let mnemonic = replace(seed, ',', ' ')
-  let generatedAccount = status_accounts.multiAccountImportMnemonic(mnemonic)
+  var generatedAccount = status_accounts.multiAccountImportMnemonic(mnemonic)
+  generatedAccount.derived = status_accounts.deriveAccounts(generatedAccount.id)
```
Comment (PascalPrecht) [inline src/status/wallet.nim:190]: The only reason we're attaching `derived` here, is because `saveAccount()` relies on that to return a `DerivedAccount` which needs the correct `address` ("correct" being the default account):

https://github.com/status-im/nim-status-client/blob/68aafaba6fdee1521bdf6075f35b1e6b75a2f2a6/src/status/libstatus/accounts.nim#L244-L262

File: src/status/libstatus/accounts.nim (hunk 1 above)
Comment (jrainville) [reply src/status/libstatus/accounts.nim:228]: I think it should be fine. I was personally a bit lost when I implemented that in the first place, so  think I misunderstood what a derived account is, hence why the flag `isADerivedAAccount` is wrong

**Review by jrainville — APPROVED** [review]
Nice finds
