### PR TITLE
fix: app crashes when adding a contact and getContactById is nil

### LINKED ISSUE #1307: Adding a contact immediatly after creating a 1:1 chat crashes the app
```
/home/richard/status/nim-status-client/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(598) onSlotCalled
/home/richard/status/nim-status-client/src/app/profile/view.nim(320) addContact
/home/richard/status/nim-status-client/src/status/contacts.nim(81) addContact
/home/richard/status/nim-status-client/src/status/contacts.nim(49) addContact
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:439: run-linux] Error 1
```

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes #1307

### CODE REVIEW

File: src/status/contacts.nim [hunk 1]
```diff
@@ -43,8 +44,24 @@ proc getContacts*(self: ContactModel): seq[Profile] =
...
+      ensName: "",
+      ensVerified: false,
+      ensVerifiedAt: 0,
+      appearance: 0,
+      ensVerificationRetries: 0,
+      systemTags: @[]
+    )
+
   let updating = contact.systemTags.contains(":contact/added")
+  echo "C"
```
Comment (jrainville) [inline src/status/contacts.nim:64]:
```suggestion
```

File: src/status/libstatus/contacts.nim [hunk 2]
```diff
@@ -39,3 +39,7 @@ proc saveContact*(id: string, ensVerified: bool, ensName: string, ensVerifiedAt:
       "localNickname": localNickname
     }]
   callPrivateRPC("saveContact".prefix, payload)
+
+proc requestContactUpdate*(): string =
```
Comment (jrainville) [inline src/status/libstatus/contacts.nim:43]: Is this used?

Comment (richard-ramos) [reply src/status/libstatus/contacts.nim:43]: oops!

**Review by jrainville — APPROVED** [review]
