### PR TITLE
fix: don't show backup message when mnemonic was imported

### LINKED ISSUE #1584: When importing seed phrase, backup-seed-phrase is redundant
After importing an account from seed phrase, the "backup seed phrase" option shouldn't be showing up as a notification

### PR DESCRIPTION
**Pull request by PascalPrecht**
As reported in #1584 the message that asks users to backup their seed phrase
is shown even when the seed phrase was imported in the first place, implying that
the mnemonic is already backed (it has to come from somewhere, right?).

This commit introduces a new `appSettings` property that is temporarily set to
determine whether or not the backup message should be shown.

It's set only temporarily because we actualy determine whether we want to show the
backup message, by checking if the account's mnemonic is still stored in the settings.
When a backup is done, Status removes the mnemonic from the profile settings.

So in order to get the right behaviour we need to make sure to remove the mnemonic
from the profile settings after the account has logged-in and originated from
an imported seed phrase. This is done by setting the mentioned property.

Closes #1584

### CODE REVIEW

File: src/app/profile/core.nim [hunk 1]
```diff
@@ -53,6 +53,7 @@ proc init*(self: ProfileController, account: Account) =
   self.view.setNewProfile(profile)
   self.view.network.setNetwork(network)
   self.view.ens.init()
+  self.view.initialized()
```
Comment (PascalPrecht) [inline src/app/profile/core.nim:56]: Preferred to have this in `loginModel` but that one is destroyed by the time we've logged-in

File: ui/main.qml [hunk 2]
```diff
@@ -138,6 +138,7 @@ ApplicationWindow {
         property var chatSplitView
         property var walletSplitView
         property var profileSplitView
+        property bool showBackupMessage: true
```
Comment (PascalPrecht) [inline ui/main.qml:141]: Might make sense to call it `removeMnemonicAfterLogin` instead to make more clear what this is about?

File: ui/main.qml [hunk 3]
```diff
@@ -361,6 +371,7 @@ ApplicationWindow {
         id: existingKey
         ExistingKey {
             onClosed: function () {
+                appSettings.showBackupMessage = true
```
Comment (jrainville) [inline ui/main.qml:374]: If it is set to true by default, I think this one here is not necessary right?

File: ui/main.qml (hunk 2 above)
Comment (jrainville) [reply ui/main.qml:141]: Yeah I think that's right. Also, it doesn't have to be a Settings property, since we don't care about saving in on multiple app reloads; the mnemonic only needs to be removed once.

So, you could probably just do a normal property called `removeMnemonicAfterLogin`, then you probably don't need all those other checks on `showBackupMessage` since the mnemonic being removed already takes care of it I think?

File: ui/main.qml [hunk 4]
```diff
@@ -214,6 +215,15 @@ ApplicationWindow {
             applicationWindow.settingsLoaded()
         }
     }
+    Connections {
+        target: profileModel
```
Comment (jrainville) [inline ui/main.qml:219]: You could add `enabled: !appSettings.showBackupMessage` here so that this Connections is only active when that flag is up, removing a tiny bit of usage.
You could obviously remove the `if` below after

**Review by jrainville — COMMENTED** [review]
I added some suggestions, hopefully they are doable

File: ui/main.qml (hunk 3 above)
Comment (PascalPrecht) [reply ui/main.qml:374]: It can theoretically happen that you first start importing an existing key but then decide to stop the process and generate a new key.
If we don't reset the property to `true` then by that point it'll be `false`. If you then generate a key and perform the login, it'll cause the app to remove the mnemonic from the db without the user having a chance to back it up.

File: ui/main.qml (hunk 2 above)
Comment (PascalPrecht) [reply ui/main.qml]: > So, you could probably just do a normal property called removeMnemonicAfterLogin,

I've update the PR accordingly, just wondering what you referring to with "normal property". Do you mean a normal prop on `appMain`?

The reason I put it originally on `Settings` was because I was approaching a client-side only solution so, indeed I wanted to keep the value around. While this is not needed anymore, I still need access to that property in different places in the app. This could also be done by putting it on `appMain` but I thought it's prolly better to rely on `appSettings` since we use that throughout the app anyways.

Thoughts?

**Review by jrainville — APPROVED** [review]
